version: "3.8"

services:
  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_USER=${KC_DB_USERNAME}
      - POSTGRES_PASSWORD=${KC_DB_PASSWORD}
      - POSTGRES_DB=${KC_DB_NAME}
    ports:
      - "${KC_DB_EXPOSED_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
