name: cd

on:
  #push:
  # branches:
  #  - cd
  repository_dispatch:
    types: [start-build]
      
env:
  #REGISTRY: ghcr.io
  #IMAGE_NAME: adorsys/kcoidvci-dispatch

  REGISTRY: 917848404243.dkr.ecr.eu-central-1.amazonaws.com
  IMAGE_NAME: kcoid4vci
  
jobs:
  build-deliver:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read
  
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout from kc-oid4vci-deployment
        uses: actions/checkout@v4
        with:
          repository: adorsys/kc-oid4vci-deployment
          #ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          token: ${{ secrets.PAT }} 
          path: deployment
          ref: issue-25638

      - name: Configure AWS credentials 
        # Programmatic authentication to aws
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ steps.login-ecr.outputs.registry }}/${{ env.IMAGE_NAME }}
        
      - name: upload image to ECR
        uses: appleboy/docker-ecr-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          repo: ${{ env.IMAGE_NAME }}
          registry: ${{ env.REGISTRY }}
          region: ${{ secrets.AWS_REGION }}

